import reflex as rx
from state import AppState
from frontend.components.threejs_component import ThreeJSViewer

def header() -> rx.Component:
    return rx.hstack(
        rx.text("World Virtual", font_size="1.2em", color="black", font_weight="bold"),
        rx.spacer(),
        rx.text("Mapa del proyecto.", margin_left="0.5em", color="black", font_size="0.8em"),
        rx.text("Libro blanco", margin_left="0.5em", color="black", font_size="0.8em"),
        rx.text("Código abierto", margin_left="0.5em", color="black", font_size="0.8em"),
        rx.button(
            AppState.selected_network,
            on_click=AppState.toggle_networks_menu,
            bg="#343a40",
            color="white",
            margin_left="0.5em",
            font_size="0.65em",
            padding="0.3em 0.6em",
            cursor="pointer",
            border_radius="4px",
        ),
        rx.cond(
            AppState.show_networks_menu,
            rx.vstack(
                rx.button("Binance Smart Chain", on_click=lambda: AppState.select_network("Binance Smart Chain"), 
                         width="100%", font_size="0.7em", padding="0.3em"),
                rx.button("Ethereum", on_click=lambda: AppState.select_network("Ethereum"), 
                         width="100%", font_size="0.7em", padding="0.3em"),
                rx.button("Polygon", on_click=lambda: AppState.select_network("Polygon"), 
                         width="100%", font_size="0.7em", padding="0.3em"),
                rx.button("Avalanche", on_click=lambda: AppState.select_network("Avalanche"), 
                         width="100%", font_size="0.7em", padding="0.3em"),
                rx.button("Arbitrum", on_click=lambda: AppState.select_network("Arbitrum"), 
                         width="100%", font_size="0.7em", padding="0.3em"),
                rx.button("Solana", on_click=lambda: AppState.select_network("Solana"), 
                         width="100%", font_size="0.7em", padding="0.3em"),
                position="absolute",
                top="100%",
                right="0",
                background_color="white",
                border="1px solid #ddd",
                border_radius="4px",
                box_shadow="0 2px 8px rgba(0,0,0,0.1)",
                z_index="1000",
                width="160px",
                align_items="stretch",
                spacing="1",
            ),
            None,
        ),
        width="100%",
        height="50px",
        background_color="#FFD700",
        align_items="center",
        padding_x="4",
        z_index="100",
        position="relative",
    )

def main_content_area() -> rx.Component:
    return rx.box(
        rx.box(
            rx.vstack(
                rx.text("Área de Contenido Principal", 
                       font_size="1.5em", 
                       font_weight="bold", 
                       color="#333"),
                rx.text("Aquí va el contenido principal de la aplicación.", 
                       font_size="1em", 
                       color="#666",
                       text_align="center"),
                rx.text("El área se ajusta automáticamente al tamaño de la ventana.", 
                       font_size="0.9em", 
                       color="#888",
                       text_align="center"),
                spacing="2",
                align_items="center",
                justify_content="center",
                height="100%",
            ),
            background_color="white",
            border="2px solid #4A90E2",
            border_radius="30px",
            box_shadow="0 4px 20px rgba(0,0,0,0.1)",
            width="90%",
            height="85%",
            padding="2rem",
            margin="auto",
            display="flex",
            align_items="center",
            justify_content="center",
        ),
        width="100%",
        height="100%",
        background_color="#228B22",
        display="flex",
        align_items="center",
        justify_content="center",
        padding="2",
    )

def Home() -> rx.Component:
    return rx.box(
        rx.vstack(
            rx.heading("Metaverso Crypto 3D", size="lg"),
            rx.text("¡Bienvenido al metaverso cripto 3D modular con Reflex!"),
            rx.divider(),
            rx.text("Ejemplo de integración Three.js como custom component:"),
            ThreeJSViewer(scene="demo_scene"),
            spacing="4",
            padding="4",
        ),
        width="100vw",
        height="100vh",
        display="flex",
        align_items="center",
        justify_content="center",
        background="linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    ) 